name: ne_gorchit
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-22.0.dev <4.0.0'

dependencies:
  http: ^1.0.0
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+4
  shared_preferences: ^2.1.1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
